### ISSUE TITLE
학식 정보 제안

### ISSUE THREAD

**Issue by HanHyunsoo** [junseok0304/haksic_chatbot#1]
[https://github.com/HanHyunsoo/OnsuYumYumYumServer](https://github.com/HanHyunsoo/OnsuYumYumYumServer)

챗봇 만드시려면 학식 정보 필요할텐데 저기 서버로 api요청하시면 메뉴 정보를 받을 수 있어요 필요하시면 사용하시면 될듯합니당.

**Comment by junseok0304** [comment]
감사합니다. API 활용하여 밥full 정보를 요청해 띄워주는 기능을 추가하도록 하겠습니다.
